FROM node:22.9.0

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar package.json y package-lock.json antes de instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto de desarrollo de Next.js
EXPOSE 3000

# Comando para iniciar el entorno de desarrollo
CMD [npm run dev]
