import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Acme } from "next/font/google";
import "@/styles/globals.css";

//components
import BarraNegra from "@/components/layout/BarraNegra";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import BurbuWhatsapp from "@/components/ui/BurbuWhatsapp";

const AcmeFont = Acme({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tienda nombre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${AcmeFont.className} antialiased`}
      >
        <BarraNegra />
        <Header />
        <BurbuWhatsapp />
        {children}
        <Footer />
      </body>
    </html>
  );
}
